name: Test-Notebooks

# Run every time a new commit is pushed.
on: push

jobs:
  # Set the job key
  test-notebooks:
    # Name the job
    name: Test Jupyter Notebooks
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          pip3 install jupyterlab
          jupyter nbconvert --execute ana-parca-parca.ipynb

